spring.application.name=anhgagifcode

# DATABASE
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.open-in-view=false

# JWT
#jwt.secret=${JWT_SECRET}
jwt.secret=

# KIOTVIET
kiotviet.api.url=https://public.kiotapi.com
kiotviet.api.retailer=
kiotviet.api.client-id=
kiotviet.api.client-secret=

# TELEGRAM BOT ALERTS
telegram.bot.token=
telegram.chat.id=